# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: Build Chocofi ZMK Firmware
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left", "corne_right"]'
      alphas: '["default"]'
      extra: '["default"]'
      tap: '["default"]'
      nav: '["default"]'
      clipboard: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["default"]'
      branches: '["default"]'
      modules: '["default"]'
