name: Build ZMK Firmware
on:
  workflow_call:
    inputs:
      board:
        description: 'Board to build for'
        required: true
        type: string
      shield:
        description: 'Shield to build for'
        required: true
        type: string
      kconfig:
        description: 'Additional Kconfig options'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify west.yml
        run: ls -l west.yml || { echo "west.yml not found"; exit 1; }

      - name: Setup ZMK
        run: |
          west init -l .
          west update || { echo "west update failed"; ls -l; exit 1; }
          ls -l zmk/app || { echo "zmk/app not found"; ls -l zmk; exit 1; }

      - name: Build firmware
        run: |
          cd zmk/app
          west build -p -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }} -DZMK_CONFIG=$GITHUB_WORKSPACE/config
          if [ -n "${{ inputs.kconfig }}" ]; then
            echo "${{ inputs.kconfig }}" >> build/zephyr/.config
            west build -p -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }} -DZMK_CONFIG=$GITHUB_WORKSPACE/config
          fi

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ inputs.board }}-${{ inputs.shield }}
          path: zmk/app/build/zephyr/*.uf2
