name: Build ZMK Firmware
on:
  workflow_call:
    inputs:
      board: { required: true, type: string }
      shield: { required: true, type: string }
      kconfig: { required: false, type: string }

jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: config

      - name: Clone ZMK
        run: |
          git clone https://github.com/zmkfirmware/zmk zmk
          cd zmk
          west init -l app
          west update

      - name: Build firmware
        run: |
          cd zmk/app
          west build -p -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }} -DCONFIG_ZMK_CONFIG=$GITHUB_WORKSPACE/config
          if [ -n "${{ inputs.kconfig }}" ]; then
            echo "${{ inputs.kconfig }}" >> build/zephyr/*.config
            west build -p -b ${{ inputs.board }} -- -DSHIELD=${{ inputs.shield }} -DCONFIG_ZMK_CONFIG=$GITHUB_WORKSPACE/config
          fi

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ inputs.board }}-${{ inputs.shield }}
          path: zmk/app/build/zephyr/*.uf2
