name: Build Chocofi Miryoku ZMK
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        board: [nice_nano_v2]
        shield: [corne_left, corne_right]
        include:
          - board: nice_nano_v2
            shield: corne_left
            kconfig: |
              CONFIG_ZMK_MOUSE=y
              CONFIG_MIRYOKU_ALPHAS=COLEMAKDH
          - board: nice_nano_v2
            shield: corne_right
            kconfig: |
              CONFIG_ZMK_MOUSE=y
              CONFIG_MIRYOKU_ALPHAS=COLEMAKDH
    with:
      board: ${{ matrix.board }}
      shield: ${{ matrix.shield }}
      kconfig: ${{ matrix.kconfig }}
